spring:
  mail:
    host:smtp.gmail.com
    port:587
    username:%Gmail account%
    password:%Gmail password%
    properties:
      mail.smtp:
        auth:true
        starttls.enable:true